add force_inclusion_values
NREL/reV pull request #234
Opened 2020-11-09 22:21 UTC by MRossol

PR for #230 
- Added force_inclusion_values to Layers class
- Added a new _force_include attr and property
- Isolate force_include layers and run them after regular layers, use np.maximum instead of np.minimum to force include layer values.

2020-11-09 22:50 UTC, grantbuster requested changes
Nice this looks great! One minor doc string comment and can you also add the force_include option to the SC agg CLI help string under the excl_dict input?

2020-11-09 22:50 UTC, grantbuster commented on reV/supply_curve/exclusions.py
> +            List of force inclusion layers
add ds_slice docstring?

2020-11-10 02:44 UTC, MRossol commented on reV/supply_curve/exclusions.py
> +            List of force inclusion layers
whoops

2020-11-10 02:44 UTC, MRossol commented
Doc strings updated

2020-11-10 16:05 UTC, grantbuster approved these changes

2020-11-10 16:08 UTC, merged